reviewers:
  # The default core reviewers.
  # Reviews may only be requested from collaborators.
  defaults:
    - dmitrymaslov13
    - gevorg-gevorgyan-saritasa
    - golovachev-yaroslav
    - timofei-maximov-saritasa
    - andrey-gazzaev
